version: '3.8'
services:
  app:
    build: ../../dsf-bpe/dsf-bpe-server-jetty/docker
    image: datasharingframework/bpe
    restart: "no"
    ports:
      - 127.0.0.1:5002:5002
    secrets:
      - db_liquibase.password
      - db_user.password
      - db_user_camunda.password
      - app_server_trust_certificates.pem
      - app_client_trust_certificates.pem
      - app_client_certificate.pem
      - app_client_certificate_private_key.pem
      - app_client_certificate_private_key.pem.password
    volumes:
      - type: bind
        source: ./process
        target: /opt/bpe/process
        read_only: true
      - type: bind
        source: ./log
        target: /opt/bpe/log
    environment:
      TZ: Europe/Berlin
      EXTRA_JVM_ARGS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5002
      DEV_DSF_BPE_DB_LIQUIBASE_PASSWORD_FILE: /run/secrets/db_liquibase.password
      DEV_DSF_BPE_DB_USER_PASSWORD_FILE: /run/secrets/db_user.password
      DEV_DSF_BPE_DB_USER_CAMUNDA_PASSWORD_FILE: /run/secrets/db_user_camunda.password
      DEV_DSF_BPE_FHIR_CLIENT_TRUST_SERVER_CERTIFICATE_CAS: /run/secrets/app_server_trust_certificates.pem
      DEV_DSF_BPE_FHIR_CLIENT_CERTIFICATE: /run/secrets/app_client_certificate.pem
      DEV_DSF_BPE_FHIR_CLIENT_CERTIFICATE_PRIVATE_KEY: /run/secrets/app_client_certificate_private_key.pem
      DEV_DSF_BPE_FHIR_CLIENT_CERTIFICATE_PRIVATE_KEY_PASSWORD_FILE: /run/secrets/app_client_certificate_private_key.pem.password
      DEV_DSF_BPE_DB_URL: jdbc:postgresql://db/bpe
      DEV_DSF_BPE_FHIR_SERVER_BASE_URL: https://fhir/fhir
      DEV_DSF_SERVER_AUTH_TRUST_CLIENT_CERTIFICATE_CAS: /run/secrets/app_client_trust_certificates.pem
    networks:
      backend:
        ipv4_address: 172.28.3.130
      fhir_bpe:
        ipv4_address: 172.28.2.3
    depends_on:
      - db

  db:
    image: postgres:15
    restart: "no"
#    ports:
#      - 127.0.0.1:5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U liquibase_user -d bpe"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      TZ: Europe/Berlin
      POSTGRES_PASSWORD_FILE: /run/secrets/db_liquibase.password
      POSTGRES_USER: liquibase_user
      POSTGRES_DB: bpe
    networks:
      backend:
        ipv4_address: 172.28.3.131
    secrets:
      - db_liquibase.password

secrets:
  db_liquibase.password:
    file: ./secrets/db_liquibase.password
  db_user.password:
    file: ./secrets/db_user.password
  db_user_camunda.password:
    file: ./secrets/db_user_camunda.password

  app_server_trust_certificates.pem:
    file: ./secrets/testca_certificate.pem
  app_client_trust_certificates.pem:
    file: ./secrets/testca_certificate.pem
  app_client_certificate.pem:
    file: ./secrets/client_certificate.pem
  app_client_certificate_private_key.pem:
    file: ./secrets/client_certificate_private_key.pem
  app_client_certificate_private_key.pem.password:
    file: ./secrets/client_certificate_private_key.pem.password

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.3.128/25
  fhir_bpe:
    external: true