version: '3.8'
services:
  app:
    image: registry:5000/datasharingframework/bpe
    restart: "no"
    healthcheck:
      test: ["CMD", "java", "-cp", "dsf_bpe.jar", "dev.dsf.bpe.StatusClient"]
      interval: 10s
      timeout: 15s
      retries: 5
    secrets:
      - db_liquibase.password
      - db_user.password
      - db_user_camunda.password
      - app_client_trust_certificates.pem
      - app_client_certificate.pem
      - app_client_certificate_private_key.pem
      - app_client_certificate_private_key.pem.password
    volumes:
      - type: bind
        source: ./plugin
        target: /opt/bpe/plugin
        read_only: true
      - type: bind
        source: ./process
        target: /opt/bpe/process
        read_only: true

      - type: bind
        source: ./log
        target: /opt/bpe/log
      - type: bind
        source: ./psn
        target: /opt/bpe/psn
    environment:
      TZ: Europe/Berlin
      DEV_DSF_BPE_DB_LIQUIBASE_PASSWORD_FILE: /run/secrets/db_liquibase.password
      DEV_DSF_BPE_DB_USER_PASSWORD_FILE: /run/secrets/db_user.password
      DEV_DSF_BPE_DB_USER_CAMUNDA_PASSWORD_FILE: /run/secrets/db_user_camunda.password
      DEV_DSF_BPE_FHIR_CLIENT_TRUST_CERTIFICATES: /run/secrets/app_client_trust_certificates.pem
      DEV_DSF_BPE_FHIR_CLIENT_CERTIFICATE: /run/secrets/app_client_certificate.pem
      DEV_DSF_BPE_FHIR_CLIENT_CERTIFICATE_PRIVATE_KEY: /run/secrets/app_client_certificate_private_key.pem
      DEV_DSF_BPE_FHIR_CLIENT_CERTIFICATE_PRIVATE_KEY_PASSWORD_FILE: /run/secrets/app_client_certificate_private_key.pem.password
      DEV_DSF_BPE_DB_URL: jdbc:postgresql://db/bpe
      DEV_DSF_BPE_FHIR_SERVER_ORGANIZATION_IDENTIFIER_VALUE: Test_TTP
      DEV_DSF_BPE_FHIR_SERVER_BASE_URL: https://ttp/fhir
      DEV_DSF_BPE_PROCESS_EXCLUDED: |
        highmedorg_executeUpdateResources/0.7.0
        highmedorg_downloadAllowList/0.7.0
        highmedorg_localServicesIntegration/0.7.0
        highmedorg_requestFeasibility/0.7.0
        highmedorg_executeFeasibility/0.7.0
        highmedorg_requestDataSharing/0.7.0
        highmedorg_executeDataSharing/0.7.0
        highmedorg_executeFeasibilityMpcMultiShare/0.7.0
        highmedorg_executeFeasibilityMpcSingleShare/0.7.0
        highmedorg_requestFeasibilityMpc/0.7.0
      # property dev.dsf.bpe.allow.list.organization should only be set for testing, do not configure property in production, potential security risk
      DEV_DSF_BPE_ALLOW_LIST_ORGANIZATION: Test_TTP
    networks:
      backend:
        ipv4_address: 172.28.3.130
      fhir_bpe:
        ipv4_address: 172.28.2.3
    extra_hosts:
      - "ttp:10.42.0.10"
      - "medic1:10.42.0.11"
      - "medic2:10.42.0.12"
      - "medic3:10.42.0.13"
    depends_on:
      - db

  db:
    image: postgres:13
    restart: "no"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U liquibase_user -d bpe"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      TZ: Europe/Berlin
      POSTGRES_PASSWORD_FILE: /run/secrets/db_liquibase.password
      POSTGRES_USER: liquibase_user
      POSTGRES_DB: bpe
    networks:
      backend:
        ipv4_address: 172.28.3.131
    secrets:
      - db_liquibase.password

secrets:
  db_liquibase.password:
    file: ./secrets/db_liquibase.password
  db_user.password:
    file: ./secrets/db_user.password
  db_user_camunda.password:
    file: ./secrets/db_user_camunda.password
    
  app_client_trust_certificates.pem:
    file: ./secrets/testca_certificate.pem
  app_client_certificate.pem:
    file: ./secrets/client_certificate.pem
  app_client_certificate_private_key.pem:
    file: ./secrets/client_certificate_private_key.pem
  app_client_certificate_private_key.pem.password:
    file: ./secrets/client_certificate_private_key.pem.password

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.3.128/25
  fhir_bpe:
    external: true