name: Java CI Build with Maven (multi-step)

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup JDK 17 with maven cache
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 17
        cache: 'maven'

    - name: mvn compile test-compile jar:jar install:install
      run: mvn --batch-mode --fail-at-end --threads 1C compile test-compile jar:jar install:install

    - name: mvn surefire:test
      run: mvn --batch-mode --fail-at-end --threads 1C surefire:test

    - name: mvn failsafe:integration-test failsafe:verify
      run: mvn --batch-mode --fail-at-end --threads 1C -D forkCount=2 failsafe:integration-test failsafe:verify